Changed publish workflow trigger to `release`

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,8 +1,8 @@
 name: Publish Package
 on:
-  push:
-    branches:
-      - master
+  release:
+    types: [ published ]
+    
 jobs:
   publish:
     runs-on: ubuntu-20.04
@@ -15,7 +15,7 @@ jobs:
           LAST_PUBLISHED_VERSION=$(cargo search glowrs --limit 1 | awk '{print $3}' | tr -d '"')
           LOCAL_VERSION=$(grep -e '^version\s*=\s*"' Cargo.toml | head -1 | cut -d '"' -f2)
           if [ "$LAST_PUBLISHED_VERSION" == "$LOCAL_VERSION" ]; then
-            echo "::set-output name=skip-publish::true"
+            exit 1 # Force a failure if the versions match
           fi
 
       - uses: Swatinem/rust-cache@v2
@@ -26,4 +26,3 @@ jobs:
 
       - name: Publish glowrs
         run: cargo publish -p glowrs --token ${{ secrets.CRATES_TOKEN }}
-        if: steps.check-version.outputs.skip-publish != 'true'
